version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py run -h 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    restart: always
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trip_analyzer

volumes:
  postgres_data:
